namespace: devopsarr
name: lidarr
version: 1.0.0 # x-release-please-version
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: 'Ansible collection for Lidarr'
license_file: LICENSE
tags:
  - lidarr
  - arr
  - music
repository: https://github.com/devopsarr/ansible-collection-lidarr
documentation: https://devopsarr.github.io/ansible-doc/collections/devopsarr/lidarr/
homepage: https://github.com/devopsarr/ansible-collection-lidarr
issues: https://github.com/devopsarr/ansible-collection-lidarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml
